In [1]:
import pandas as pd

In [2]:
data = "../data/auto.json"

## **CarNumber в качестве индекса**

In [3]:
df = pd.read_json(data, orient="records")

In [4]:
df = df.set_index("CarNumber")

## **Выборки**

### **Строки, где штрафы больше 2 100**

In [5]:
df[df["Fines"] > 2100]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
E432XX77RUS        1   6500.000000      Toyota    Camry
92918M178RUS       1   5700.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
E40577152RUS       1   8594.586466        Ford    Focus
...              ...           ...         ...      ...
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
O22097197RUS       1  24300.000000        Ford    Focus
M0309X197RUS       1  22300.000000        Ford    Focus
H419XE197RUS       2   8594.586466      Toyota  Corolla

[455 rows x 4 columns]

### **Cтроки, где штрафы больше 2 100, а возврат (Refund) равен 2**

In [6]:
df[(df["Fines"] > 2100) & (df["Refund"] == 2)]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
707987163RUS       2   2200.000000        Ford    Focus
K330T8197RUS       2   8200.000000       Skoda  Octavia
M592CH197RUS       2   8594.586466       Skoda  Octavia
...              ...           ...         ...      ...
O136HO197RUS       2   7800.000000      Toyota  Corolla
O68897197RUS       2  12300.000000        Ford    Focus
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
H419XE197RUS       2   8594.586466      Toyota  Corolla

[309 rows x 4 columns]

### **Строки, где модель входит в список: ['Focus', 'Corolla']**

In [7]:
df[df["Model"].isin(["Focus", "Corolla"])]

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
H234YH197RUS       2   6000.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[593 rows x 4 columns]

### **Строки, где номер автомобиля входит в список: ['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS']**

In [8]:
df[
    df.index.isin(
        ["Y7689C197RUS", "92928M178RUS", "7788KT197RUS", "H115YO163RUS", "X758HY197RUS"]
    )
]

              Refund          Fines  Make  Model
CarNumber
92928M178RUS       1    8594.586466  Ford  Focus
H115YO163RUS       1    2200.000000  Ford  Focus
7788KT197RUS       2   12000.000000  Ford  Focus
X758HY197RUS       2   24200.000000  Ford  Focus
X758HY197RUS       2   72600.000000  Ford  Focus
Y7689C197RUS       1   27000.000000  Ford  Focus
92928M178RUS       1     600.000000  Ford  Focus
H115YO163RUS       1    8594.586466  Ford  Focus
H115YO163RUS       2    1100.000000  Ford  Focus
7788KT197RUS       2    8594.586466  Ford  Focus
7788KT197RUS       1   20000.000000  Ford  Focus
X758HY197RUS       2  145200.000000  Ford  Focus
92928M178RUS       1    1200.000000  Ford  Focus
Y7689C197RUS       2    9000.000000  Ford  Focus
Y7689C197RUS       2   45000.000000  Ford  Focus
7788KT197RUS       2    4000.000000  Ford  Focus
Y7689C197RUS       1   36000.000000  Ford  Focus
92928M178RUS       2    3000.000000  Ford  Focus

## **Агрегации по Make и Model**

### **Медианные значения штрафов, сгруппированные по Make**

In [9]:
df.groupby("Make")["Fines"].median()

Make
Audi          4200.0
BMW           6500.0
Ford          3500.0
Skoda         3250.0
Toyota        7700.0
Volkswagen    4300.0
Volvo         8500.0
Name: Fines, dtype: float64

In [22]:
df.groupby(['Make', 'Model']).agg('Fines').count()

Make        Model
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen  Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Name: Fines, dtype: int64

### **Медианные значения штрафов, сгруппированные по Make и Model**

In [10]:
df.groupby(["Make", "Model"])["Fines"].median()

Make        Model
Ford        Focus      3500.0
            Mondeo     7650.0
Skoda       Octavia    3250.0
Toyota      Camry      7700.0
            Corolla    7700.0
Volkswagen  Golf       4800.0
            Jetta      2800.0
            Passat     3500.0
            Touareg    5800.0
Name: Fines, dtype: float64

### **Количество штрафов, сгруппированное по Make и Model**

In [11]:
df.groupby(["Make", "Model"])["Fines"].agg(["count"])

                    count
Make       Model
Ford       Focus      575
           Mondeo       6
Skoda      Octavia     48
Toyota     Camry       16
           Corolla     18
Volkswagen Golf        20
           Jetta        6
           Passat      22
           Touareg      5

### **Минимальные и максимальные штрафы, сгруппированные по Make и Model**

In [12]:
df.groupby(["Make", "Model"])["Fines"].agg(["min", "max"])

                       min            max
Make       Model
Ford       Focus     100.0  180000.000000
           Mondeo   1100.0   46200.000000
Skoda      Octavia   300.0  145000.000000
Toyota     Camry     500.0   22400.000000
           Corolla   900.0   34300.000000
Volkswagen Golf      200.0  168000.000000
           Jetta     500.0   46000.000000
           Passat    100.0   29700.000000
           Touareg   500.0    8594.586466

### **Стандартное отклонение штрафов, сгруппированное по Make и Model**

In [13]:
df.groupby(["Make", "Model"])["Fines"].agg(["std"])

                             std
Make       Model
Ford       Focus    15041.269437
           Mondeo   18987.329108
Skoda      Octavia  24339.742174
Toyota     Camry     6410.250654
           Corolla   9629.325617
Volkswagen Golf     36950.839950
           Jetta    17743.026799
           Passat    6969.739135
           Touareg   3461.778173

## **Агрегации по номерам автомобилей**

### **Номера автомобилей, сгруппированные по количеству штрафов в порядке убывания**

In [14]:
car_counts = df.groupby(df.index).size().sort_values(ascending=False)

In [15]:
car_counts

CarNumber
Y7689C197RUS    4
92928M178RUS    4
7788KT197RUS    4
H115YO163RUS    3
X758HY197RUS    3
               ..
E42577152RUS    1
E42377152RUS    1
E41977152RUS    1
E41577152RUS    1
H917TC36RUS     1
Length: 531, dtype: int64

### **Все строки, соответствующие топ-1 номеру**

In [16]:
df[df.index == car_counts.idxmax()]

              Refund    Fines  Make  Model
CarNumber
Y7689C197RUS       1  27000.0  Ford  Focus
Y7689C197RUS       2   9000.0  Ford  Focus
Y7689C197RUS       2  45000.0  Ford  Focus
Y7689C197RUS       1  36000.0  Ford  Focus

### **Номера автомобилей, сгруппированные по сумме штрафов в порядке убывания**

In [17]:
fines_sum = df.groupby(df.index)["Fines"].sum().sort_values(ascending=False)

In [18]:
fines_sum

CarNumber
X758HY197RUS    242000.0
9020YC197RUS    217500.0
M0279X197RUS    216000.0
Y352O8197RUS    207200.0
Y778EE197RUS    192000.0
                  ...
83218C154RUS       100.0
Y195O8161RUS       100.0
K376HE161RUS       100.0
705787163RUS       100.0
K326T8197RUS       100.0
Name: Fines, Length: 531, dtype: float64

### **Все строки, соответствующие топ-1 номеру по сумме штрафов**

In [19]:
df[df.index == fines_sum.idxmax()]

              Refund     Fines  Make  Model
CarNumber
X758HY197RUS       2   24200.0  Ford  Focus
X758HY197RUS       2   72600.0  Ford  Focus
X758HY197RUS       2  145200.0  Ford  Focus

### **«Есть ли номера автомобилей, привязанные к разным моделям?»**

In [20]:
df.groupby(df.index)["Model"].nunique()[lambda x: x > 1]

Series([], Name: Model, dtype: int64)